version: '3'

services:

  as2-proxy-service:
    container_name: as2-proxy-service
    hostname: as2-proxy-service
    build:
      context: ./as2-proxy-service
      dockerfile: Dockerfile
    ports:
     - 80:80
    networks:
      customnetwork:
        ipv4_address: 172.24.0.2

  as2-db-service:
    container_name: as2-db-service
    hostname: as2-db-service
    image: postgres:12.12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: as2user
      POSTGRES_PASSWORD: eEEkp7Bb7q3xgL
    volumes:
      - ./data-volume/postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      customnetwork:
        ipv4_address: 172.24.0.3

  as2-redis-service:
    container_name: as2-redis-service
    hostname: as2-redis-service
    image: redis:latest
    volumes:
      - ./data-volume/redis:/data
    ports:
      - "6379:6379"
    networks:
      customnetwork:
        ipv4_address: 172.24.0.5

  as2-app-service:
    container_name: as2-app-service
    hostname: as2-app-service
    environment:
      DB_USER: as2user
      DB_PASSWORD: eEEkp7Bb7q3xgL
      DB_HOST: as2-db-service
      DB_PORT: 5432
      DB_DATABASE: postgres
      REDIS_HOST: as2-redis-service
      REDIS_PORT: 6379
    build:
      context: ./as2-app-service
      dockerfile: Dockerfile
    ports:
     - 8000:8000
    networks:
      customnetwork:
        ipv4_address: 172.24.0.4
    depends_on:
      - as2-redis-service
      - as2-db-service
      - as2-proxy-service

networks:
  customnetwork:
    ipam:
     config:
       - subnet: 172.24.0.0/16